name: Windows Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    permissions:
      actions: write
      pages: write
      contents: write
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build SimLibs
        shell: cmd
        run: build simlibs_debug